const products =[
    {
        'pro_id': '1',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls whilw working calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4,
        'numReviews': 12,
    },
    {
        'pro_id': '2',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls whilw working calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        'pro_id': '3',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls whilw working calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 5,
        'numReviews': 12,
    },
    {
        'pro_id': '4',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls whilw working calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 2.5,
        'numReviews': 12,
    },
    {
        'pro_id': '5',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls whilw working calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 2.5,
        'numReviews': 12,
    },
    {
        'pro_id': '6',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/images/airpods.jpg',
        'description': 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls whilw working calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
]
export default products;